### ISSUE TITLE
DescriptiveUpdaterService should update host_collections

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator#316]
When a request is made to the DescriptivesController#update endpoint
And the request includes JSON for the `host_collections` array
DescriptiveUpdaterService should update the host_collections relationships to match the JSON payload

Current behavior:
Value in JSON is added to existing `host_collections` array, old values are persisted

**Comment by bbarberBPL** [comment]
So in order to do this we're going to have to change how we ingest host collection values. Rather than passing just an array of strings we're going to have to pass an array of hashes ie. `{ name: 'Host collection Val' }` that way we can then allow it to be destroyed ie. `{ name: 'Host Collection Val, _destroy: '1' }`. We're also going to need to update this in Commonwealth_3
